### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by Ratismal**
Enjoy!

### CODE REVIEW

**Comment by bubmet** [comment]
good job cart

**Comment by Ratismal** [comment]
@bubmet crowdin is going apeshit crazy aaaa

**Comment by NegativeCoffee** [comment]
Top 10 most horrible war scenes

**Comment by bubmet** [comment]
@Ratismal I see
https://hack-my-mainfra.me/cce830.png

**Comment by Ratismal** [comment]
@bubmet goddamnit, I'll see if there's a way to make it not spazz out 24/7

**Comment by Saederup92** [comment]
Wew

**Pull request merged**
